XBlog/models.py
#!/usr/bin/env python
# coding:utf-8

from datetime import datetime

import bleach
from flask import current_app
from markdown import markdown
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin, AnonymousUserMixin
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer


from . import db, login_manager


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin, db.Model):
    __tablename__ = "users"
    id = db.Column(db.Integer, unique=True, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(64))

    @property
    def password(self):
        raise AttributeError("password is not a readable attribute")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def generate_reset_token(self, expiration=3600):
        s = Serializer(current_app.config.get("SECRET_KEY"), expiration=expiration)
        return s.dumps({"reset", self.id})

    def reset_password(self, token, new_password):
        s = Serializer(current_app.config.get("SECRET_KEY"))
        try:
            data = s.loads(token)
        except:
            return False
        if data.get("reset") != self.id:
            return False
        self.password = new_password
        db.session.add(self)
        return True

    @staticmethod
    def init_admin():
        db.create_all()
        u = User()
        u.email = current_app.config.get("ADMIN")
        u.password = current_app.config.get("ADMIN_PASSWORD")
        db.session.add(u)
        db.session.commit()

class About(db.Model):
    __tablename__ = "about_me"
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.Text)
    body_html = db.Column(db.Text)
    user = db.Column(db.Integer, db.ForeignKey("users.id"))

    @staticmethod
    def on_changed_body(target, value, oldvalue, initiator):
        allowed_tags = ["a", "abbr", "acronym", "b", "blockquote", "code",
                        "em", "i", "li", "ol", "pre", "strong", "ul", "h1",
                        "h2", "h3", "p", "span", "br"]
        target.body_html = bleach.linkify(bleach.clean(
            markdown(value, output_format="html"),
            tags=allowed_tags))


db.event.listen(About.body, "set", About.on_changed_body)


class Category(db.Model):
    __tablename__ = "categories"
    id = db.Column(db.Integer, primary_key=True)
    category_name = db.Column(db.String(64))
    timestamp = db.Column(db.DateTime(), index=True, default=datetime.utcnow)
    posts = db.Column(db.Integer, db.ForeignKey("posts.id"))


class Post(db.Model):
    __tablename__ = "posts"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.Text)
    nature = db.Column(db.String(64))
    body = db.Column(db.Text)
    timestamp = db.Column(db.DateTime(), index=True, default=datetime.utcnow)
    body_html = db.Column(db.Text)
    about_this_article = db.Column(db.Text)
    about_this_article_html = db.Column(db.Text)
    author = db.Column(db.Integer, db.ForeignKey("users.id"))
    categories = db.Column(db.String(64), db.ForeignKey("categories.category_name"))

    @staticmethod
    def on_changed_body(target, value, oldvalue, initiator):
        target.body_html = markdown(value, output_format="html")

    @staticmethod
    def on_changed_about(target, value, oldvalue, initiator):
        target.about_this_article_html = markdown(value, output_format="html")


db.event.listen(Post.about_this_article, "set", Post.on_changed_about)
db.event.listen(Post.body, "set", Post.on_changed_body)


class LevMessage(db.Model):
    __tablename__ = "leaving_message"
    id = db.Column(db.Integer, primary_key=True)
    user_name = db.Column(db.String(64))
    user_email = db.Column(db.String(64))
    timestamp = db.Column(db.DateTime(), index=True, default=datetime.utcnow)
    user_site = db.Column(db.String(64))
    message = db.Column(db.Text)
    message_html = db.Column(db.Text)

    @staticmethod
    def on_changed_body(target, value, oldvalue, initiator):
        target.message_html = markdown(value, output_format="html")

db.event.listen(LevMessage.message, "set", LevMessage.on_changed_body)

class AnonymousUser(AnonymousUserMixin):
    def is_administrator(self):
        return False


login_manager.anonymous_user = AnonymousUser

XBlog/main/forms.py
#!/usr/bin/env python
# coding:utf-8

from flask_wtf import FlaskForm
from flask_pagedown.fields import PageDownField

from wtforms import StringField, SubmitField, TextAreaField, PasswordField
from wtforms import BooleanField, SelectField, ValidationError
from wtforms.validators import Required, Length, Regexp, Email, URL


class LoginForm(FlaskForm):
    email = StringField("Email", validators=[
        Required(), Length(1, 64), Email()])
    password = PasswordField("Password", validators=[Required()])
    remember_me = BooleanField("Keep me logged in")
    submit = SubmitField("Log In")


class EditAbout(FlaskForm):
    about = PageDownField("ABOUT")
    submit = SubmitField("Submit")


class EditPostForm(FlaskForm):
    title = StringField("Title", validators=[Required()])
    categories = StringField("Category", validators=[Required(), Length(1, 64)])
    nature = SelectField(u"type", coerce=str)
    about_this_article = PageDownField("About this article", validators=[Required()])
    body = PageDownField("WRITE", validators=[Required()])
    submit = SubmitField("Submit")

    def __init__(self, *args, **kwargs):
        super(EditPostForm, self).__init__(*args, **kwargs)

        self.nature.choices = [("tecnology", u"技术"), ("life", u"生活")]


class LeaveMessageForm(FlaskForm):
    user_name = StringField(u"昵称(英文)*:", validators=[
        Required(),
        Length(1, 64), Regexp("^[A-Za-z][A-Za-z0-9_.]*$", 0,
                              "Usernames must have only letters, "
                              "numbers, dots or underscores")
    ])
    user_email = StringField(u"邮箱(非必须)", validators=[Email()])
    user_site = StringField(u"您的主页(http://example.com)*", validators=[Length(1, 64), URL()])
    body = PageDownField(u"您的留言*", validators=[Required(), Length(1, 200)])
    submit = SubmitField(u"提交")

XBlog/__init__.py
#!/usr/bin/env python
# coding:utf-8

from flask import Flask
from flask_moment import Moment
from flask_mail import Mail
from flask_login import LoginManager
from flask_pagedown import PageDown
from flask_sqlalchemy import SQLAlchemy, SignallingSession

from config import config


class NewSQLAlchemy(SQLAlchemy):
    def create_session(self, options):
        options["autoflush"] = False
        return SignallingSession(self, **options)


mail = Mail()
moment = Moment()
db = NewSQLAlchemy()
login_manager = LoginManager()
pagedown = PageDown()
login_manager.session_protection = "strong"
login_manager.login_view = "auth.login"


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    config[config_name].init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    pagedown.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    return app

XBlog/main/__init__.py
#!/usr/bin/env python
# coding:utf-8

from flask import Blueprint

main = Blueprint("main", __name__)

from . import views, errors

XBlog/main/views.py
from datetime import datetime
from collections import Counter
from flask import render_template, request, flash, redirect, url_for, current_app, abort
from flask_login import login_required, current_user
from . import main
from ..models import Post, About, Category, LevMessage
from .. import db
from .forms import EditPostForm, EditAbout, LeaveMessageForm


@main.route("/", methods=["GET", "PSOT"])
def index():
    page = request.args.get("page", 1, type=int)
    pagination = Post.query.filter_by(nature="tecnology").order_by(
        Post.timestamp.desc()).paginate(
        page, per_page=current_app.config["POSTS_PER_PAGE"],
        error_out=False)
    posts = pagination.items
    IS_ADMIN = ((not current_user.is_anonymous)
                and current_user.email == current_app.config.get("ADMIN"))
    return render_template("index.html",
                           posts=posts,
                           IS_ADMIN=IS_ADMIN,
                           pagination=pagination,
                           current_time=datetime.utcnow(),
                           Category=Category)


@main.route("/life")
def life():
    IS_ADMIN = ((not current_user.is_anonymous)
                and current_user.email == current_app.config.get("ADMIN"))
    page = request.args.get("page", 1, type=int)
    pagination = Post.query.filter_by(nature="life").order_by(
        Post.timestamp.desc()).paginate(
        page, per_page=current_app.config["POSTS_PER_PAGE"],
        error_out=False)
    posts = pagination.items
    return render_template("index.html",
                           posts=posts,
                           IS_ADMIN=IS_ADMIN,
                           Category=Category,
                           pagination=pagination,
                           current_time=datetime.utcnow(),
                           )


@main.route("/category/<categy>")
def category(categy):
    all_category = Category.query.all()
    categories = Counter([item.category_name for item in all_category])
    page = request.args.get("page", 1, type=int)
    pagination = Category.query.filter_by(category_name=categy).order_by(
        Category.timestamp.desc()).paginate(
        page, per_page=current_app.config["POSTS_PER_PAGE"],
        error_out=False)
    posts_id = [item.posts for item in pagination.items]
    posts = [Post.query.get_or_404(pid) for pid in posts_id]
    if posts is None:
        abort(404)
    return render_template("category.html", current_time=datetime.utcnow(),
                           request=request, posts=posts, categories=categories,
                           pagination=pagination, Category=Category)

@main.route("/new", methods=["GET", "POST"])
@login_required
def new():
    form = EditPostForm()
    if form.validate_on_submit():
        post = Post()
        post.title = form.title.data
        post.nature = form.nature.data
        post.categories = categoriy_string = form.categories.data
        post.about_this_article = form.about_this_article.data
        post.body = form.body.data
        post.timestamp = datetime.utcnow()
        post.author = current_user._get_current_object().id
        db.session.add(post)
        db.session.commit()
        post_id = post.id
        categories = [item.strip() for item in categoriy_string.split(",")]
        for category in categories:
            categy = Category()
            categy.category_name = category
            categy.posts = post_id
            db.session.add(categy)
        db.session.commit()

        flash("Publish succeed.")
        return redirect(url_for("main.index"))
    return render_template("edit_post.html", form=form)


@main.route("/post/<int:pid>", methods=["GET", "POST"])
def post(pid):
    _post = Post.query.get_or_404(pid)
    # form = CommentForm()
    # if form.validate_on_submit():
    #     comment = Comment(body=form.body.data,
    #                       post=post,
    #                       author=current_user._get_current_object())
    #     db.session.add(comment)
    #     flash("Your comment has been published.")
    #     return redirect(url_for("main.post", id=post.id, page=-1))
    # page = request.args.get("page", 1, type=int)
    # if page == -1:
    #     page = (post.comments.count() -1) / \
    #         current_app.config["X2EX_POSTS_PER_PAGE"] + 1
    # pagination = post.comments.order_by(Comment.timestamp.asc()).paginate(
    #     page, per_page=current_app.config["X2EX_POSTS_PER_PAGE"],
    #     error_out=False)
    # comments = pagination.items
    return render_template("post.html", posts=[_post], Category=Category) # , form=form,
    #                        comments=comments, pagination=pagination)


@main.route("/about")
def about():
    about_me = About.query.first()
    return render_template("about.html",
                           about=about_me,
                           user=current_user,
                           admin=current_app.config.get("ADMIN"))


@main.route("/edit/<int:pid>", methods=["GET", "POST"])
@login_required
def edit(pid):
    post = Post.query.get_or_404(pid)
    form = EditPostForm()
    if form.validate_on_submit():
        post.body = form.body.data
        post.title = form.title.data
        post.nature = form.nature.data
        post.categories = form.categories.data
        post.timestamp = datetime.utcnow()
        post.author = current_user._get_current_object().id
        db.session.add(post)
        flash("The post has been updated.")
        return redirect(url_for("main.post", pid=post.id))
    form.title.data = post.title
    form.nature.data = post.nature
    form.categories.data = post.categories
    form.about_this_article.data = post.about_this_article
    form.body.data = post.body
    return render_template("edit_post.html", form=form)


@main.route("/delete/<int:pid>")
@login_required
def delete(pid):
    p = Post.query.filter_by(id=pid).first()
    db.session.delete(p)
    db.session.commit()
    category = Category.query.filter_by(posts=pid).all()
    for ca in category:
        db.session.delete(ca)
        db.session.commit()
    flash("You have delete the article!")
    db.session.commit()
    return redirect(url_for("main.index"))

@main.route("/edabout", methods=["GET", "POST"])
@login_required
def edabout():
    about = About.query.filter_by(user=current_user.id).first()
    about = About() if about is None else about
    form = EditAbout()
    if form.validate_on_submit():
        about.body = form.about.data
        about.user = current_user.id
        db.session.add(about)
        return redirect(url_for("main.about"))
    form.about.data = about.body
    return render_template("edit_about.html", form=form)

@main.route("/message_board", methods=["GET", "POST"])
def message_board():
    form = LeaveMessageForm()
    page = request.args.get("page", 1, type=int)
    pagination = LevMessage.query.order_by(
        LevMessage.timestamp.desc()).paginate(
        page, per_page=current_app.config["LEVMEG_PER_PAGE"],
        error_out=False)
    msg = pagination.items
    if form.validate_on_submit():
        Message = LevMessage()
        Message.user_name = form.user_name.data
        Message.user_email = form.user_email.data
        Message.user_site = form.user_site.data
        Message.timestamp = datetime.utcnow()
        Message.message = form.body.data
        db.session.add(Message)
        return redirect(url_for("main.message_board"))
    return render_template("message_board.html",
                           msg=msg,
                           form=form,
                           pagination=pagination)

XBlog/templates/_index.html
{% for post in posts %}
{% set id = post.id %}
{% set categories = Category.query.filter_by(posts=id) %}
  <div class="col s12 m12">
    <div class="card hoverable sticky-action">
    <div class="card-content">
      <a href="{{ url_for('main.post', pid=post.id) }}" class="card-title activator grey-text text-darken-3"><h4>{{ post.title }}</h4></a>
      <span class="card-title activator grey-text text-darken-4"><i class="material-icons right">more_vert</i></span>
      <div><p><i class="tiny material-icons" style="vertical-align: middle">today</i>{{ post.timestamp.strftime(format="%Y-%m-%d") }}</p></div>
      <br/>
      {% if post.about_this_article_html %}
      <p>{{ post.about_this_article_html | safe }}</p>
      {% else %}
      {{ post.about_this_article }}
      {% endif %}
    </div>
    <div class="card-action">
      <a href="{{ url_for('main.post', pid=post.id) }}">Read More</a>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">标签<i class="material-icons right">close</i></span>
        {% for category in categories %}
        <a href="{{ url_for('main.category', categy=category.category_name) }}">
        <div class="chip cyan accent-2">{{ category.category_name }}</div>
        </a>
        {% endfor %}

        {% if IS_ADMIN %}
        <span class="card-title grey-text text-darken-4">Root</span>
        <a href="{{ url_for('main.delete', pid=post.id) }}">
        <div class="chip red darken-1 white-text">删除</div>
        </a>
        <a href="{{ url_for('main.edit', pid=post.id) }}">
        <div class="chip green accent-3 white-text">编辑</div>
        </a>
        {% endif %}
    </div>
  </div>
  </div>

{% endfor %}

XBlog/templates/_life.html
{% for post in lifes %}
  <div class="col s12 m12">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">{{ post.title }}</span>
        <i class="small material-icons today"></i>
        {% if post.about_this_article_html %}
        <p>{{ post.about_this_article_html | safe }}</p>
        {% else %}
        {{ post.about_this_article }}
        {% endif %}
      </div>
    </div>
 <a class='dropdown-button btn' href='#' data-activates='dropdown1'>Tags</a>

  <!-- Dropdown Structure -->
  <ul id='dropdown1' class='dropdown-content'>
    {% for category in Category.query.filter_by(posts=post.id).all() %}
    <li><a href="{{ url_for('main.category', categy=category.category_name) }}">{{ category.category_name }}</a></li>
    <li class="divider"></li>
    {% endfor %}
  </ul>
  </div>
{% endfor %}

XBlog/templates/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
<ul class="pagination">
  <li{% if not pagination.has_perv %} class="disabled"{% endif %}>
    <a href="{% if pagination.has_perv %}{{ url_for(endpoint,
    page=pagination.page -1, **kwargs) }}{% else %}#{% endif %}">
      &laquo;
    </a>
  </li>
  {% for p in pagination.iter_pages() %}
  {% if p %}
  {% if p == pagination.page %}
  <li class="active">
    <a href="{{ url_for(endpoint, page=p, **kwargs) }}">{{ p }}</a>
  </li>
  {% else %}
  <li>
    <a href="{{ url_for(endpoint, page=p, **kwargs) }}">{{ p }}</a>
  </li>
  {% endif %}
  {% else %}
  <li class="disabled"><a href="#">&hellip;</a></li>
  {% endif %}
  {% endfor %}
  <li{% if not pagination.has_next %} class="disabled"{% endif %}>
    <a href="{% if pagination.has_next %}{{ url_for(endpoint,
    page=pagination.page + 1, **kwargs) }}{% else %}#{% endif %}">
      &raquo;
    </a>
  </li>
</ul>
{% endmacro %}

XBlog/templates/_posts.html
<ul class="posts">
    {% for post in posts %}
    <div class="jumbotron modal-content" style="width: 100%">
        <center><h1>{{ post.title }}</h1></center>
        <p class="text-muted">{{ post.timestamp.strftime(format="%Y-%m-%d") }}</p>
        {% for category in Category.query.filter_by(posts=post.id) %}
        <p><a href="{{ url_for('main.category', categy=category.category_name) }}" style="color: #337ab7;float:left">
            <span class="label label-success">{{ category.category_name }}</span>
        </a></p>
        {% endfor %}
        <div class="post-body">
          {% if post.body_html %}
          {{ post.body_html | safe }}
          {% else %}
          {{ post.body }}
          {% endif %}
        </div>

    <p><a href="{{ url_for('main.edit', pid=post.id) }}" class="btn btn-danger read-more">编辑</a></p>
    </div>
    {% endfor %}
</ul>

{% for post in posts %}
<div class="rol s12 m16">
<div class="card sticky-action">
  <div class="card-action">...</div>

  <div class="card-reveal">...</div>
</div>

XBlog/templates/_tools.html
<p>hello tools</p>

XBlog/templates/about.html
{% extends "base.html" %}

{% block title %}About{% endblock %}

{% block navbar_style %}
style="margin-bottom:40px"
{% endblock %}

{% block page_content %}
<div class="row">
    <div class="col s12">
      <div class="card hoverable white">
        <div class="card-content">
            {{ about.body_html | safe }}
        </div>
        {% if user.email == admin %}
        <div class="card-action">
        <a href="{{ url_for('main.edabout') }}" class="btn btn-danger">编辑</a>
        </div>
        {% endif %}
      </div>
    </div>
    <div class="col s12">
        <div class="card hoverable">
        <div class="card-content">
            <!-- 多说评论框 start -->
            <div class="ds-thread" data-thread-key="-2" data-title="About" data-url="{{ url_for('main.about') }}"></div>
            <!-- 多说评论框 end -->
            <!-- 多说公共JS代码 start (一个网页只需插入一次) -->
            <script type="text/javascript">
            var duoshuoQuery = {short_name:"xiahei"};
                (function() {
                var ds = document.createElement('script');
                ds.type = 'text/javascript';ds.async = true;
                ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
                ds.charset = 'UTF-8';
                (document.getElementsByTagName('head')[0] 
                || document.getElementsByTagName('body')[0]).appendChild(ds);
                })();
                </script>
            <!-- 多说公共JS代码 end -->
        </div>
        </div>
    </div>
</div>
{% endblock %}

XBlog/templates/base.html
{% extends "bootstrap_to_material/base.html" %}

{% block title %} x1ah's blog {% endblock %}

{% block hscript %}
    <script>
        function side()
        {
            $(".button-collapse").sideNav();
            $('.carousel.carousel-slider').carousel({full_width: true});
            $(document).ready(function() {
                $('select').material_select();
                $('.tooltipped').tooltip({delay: 50});
            });
        }
    </script>
{% endblock %}


{% block head %}
    {{ super() }}
    <link rel="shortcut icon" href="{{ url_for("static", filename="favicon.ico") }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for("static", filename="favicon.ico") }}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{ url_for("static", filename="css/materialize.min.css") }}" media="screen,projection"/>
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
{% endblock %}

{% block body_attribs %}
    onload="side();"
{% endblock %}

{% block body_style %}
style="
    background-image:url('https://static.v2ex.com/tiles/idev.png');
    background-size: cover;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;"
{% endblock %}

{% block navbar %}
<div class="fixed-action-btn horizontal">
   <a class="btn-floating btn-large red">
      <i class="material-icons">menu</i>
   </a>
   <ul>
      <li><a class="btn-floating red button-collapse" data-activates="mobile-demo"><i class="material-icons">menu</i></a></li>
      <li><a href="javascript:scroll(0, 0)" class="btn-floating green"><i class="material-icons">publish</i></a></li>
   </ul>
</div>

<nav {% block navbar_style %}{% endblock %}>
    <div class="nav-wrapper grey darken-3">
    <div class="container">
      <a href="/" class="brand-logo">x1ah</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="/about">About</a></li>
        <li><a href="/life">Life</a></li>
        <li><a href="/message_board">留言板</a></li>
        <li><a href="http://github.com/x1ah">GitHub</a></li>
        {% if current_user.email %}
        <li><a href="/new">Write</a></li>
        <li><a href="/logout">Log Out</a></li>
        {% else %}
        <li><a href="/login">Log In</a></li>
        {% endif %}
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="/">Home</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/life">Life</a></li>
        <li><a href="http://github.com/x1ah">GitHub</a></li>
        <li><a href="/message_board">留言板</a></li>
        {% if current_user.email %}
        <li><a href="/new">Write</a></li>
        <li><a href="/logout">Log Out</a></li>
        {% else %}
        <li><a href="/login">Log In</a></li>
        {% endif %}
      </ul>
    </div>
    </div>
  </nav>
{% endblock %}


{% block content %}
    <div class="container">
        {% block page_content %}{% endblock %}
        {% block tags %}{% endblock %}
    </div>
{% endblock %}

{% block footer %}
<footer class="page-footer grey darken-3">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Hello my world</h5>
        <p class="grey-text text-lighten-4">Live free or die!<br/>Keep It Simple! Stupid!</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">友情链接</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="http://ajucs.com">Aju</a></li>
          <li><a class="grey-text text-lighten-3" href="http://wuwenfu.cn">吴文付的博客</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2016 Copyright Text
    <a class="grey-text text-lighten-4 right" href="http://github.com/x1ah/XBlog">Fork me on GitHub</a>
    </div>
  </div>
</footer>
{% for message in get_flashed_messages() %}
<script>
    Materialize.toast('{{ message }}', 3000, 'rounded');
</script>
{% endfor %}
{% endblock %}

{% block scripts %}
    <script
        src="https://code.jquery.com/jquery-2.2.4.min.js"
        integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
        crossorigin="anonymous">
    </script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/materialize.min.js') }}"></script>

    {{ moment.include_moment() }}
    {{ moment.lang("zh-CN")}}
{% endblock %}

XBlog/templates/category.html
{% extends "index.html" %}
{% import "_macros.html" as macros %}

{% block display %}{% endblock %}

{% block page_content %}
<div class="row">
{% include "_index.html" %}
</div>
{% endblock %}

XBlog/templates/post.html
{% extends "base.html" %}
{% import "bootstrap_to_material/wtf.html" as wtf %}

{% block title %}Post{% endblock %}

{% block navbar_style %}
style="margin-bottom:40px"
{% endblock %}

{% block page_content %}
    {% for post in posts %}
    <!--
  <nav style="margin-bottom: 30px">
    <div class="nav-wrapper grey darken-3">
      <div class="col s12">
        <a href="#!" class="breadcrumb">当前位置</a>
        <a href="/" class="breadcrumb">Home</a>
        <a href="/{{ post.nature }}" class="breadcrumb">{{ post.nature }}</a>
      </div>
    </div>
  </nav>
    -->
    <div class="row">
        <div class="col s12">
          <div class="card z-depth-5 white">
            <div class="card-content">
                <span class="card-title black-text"><h3><center>{{ post.title }}</center></h3></span>
                <div>
                    <p><center><i class="tiny material-icons" style="vertical-align: middle">today</i>{{ post.timestamp.strftime(format="%Y-%m-%d") }}</center></p>
                    <br/>
                </div>
                {% if post.body_html %}
                {{ post.body_html | safe }}
                {% else %}
                {{ post.body }}
                {% endif %}
            </div>
            {% if current_user.email %}
            <div class="card-action">
            <a href="{{ url_for('main.edit', pid=post.id) }}" class="btn btn-danger read-more">编辑</a>
            </div>
            {% endif %}
          </div>
        </div>
        <div class="col s12">
          <div class="card hoverable">
            <div class="card-content">
              <!-- 多说评论框 start -->
              <div class="ds-thread" data-thread-key="{{ post.id }}" data-title="{{ post.title }}" data-url="{{ url_for('main.post', pid=post.id) }}"></div>
                <!-- 多说评论框 end -->
                <!-- 多说公共JS代码 start (一个网页只需插入一次) -->
                <script type="text/javascript">
                var duoshuoQuery = {short_name:"xiahei"};
                  (function() {
                    var ds = document.createElement('script');
                    ds.type = 'text/javascript';ds.async = true;
                    ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
                    ds.charset = 'UTF-8';
                    (document.getElementsByTagName('head')[0] 
                    || document.getElementsByTagName('body')[0]).appendChild(ds);
                  })();
                  </script>
                <!-- 多说公共JS代码 end -->
            </div>
          </div>
        </div>
    </div>
    {% endfor %}
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}